pipeline {
    agent any
    parameters {
        choice(
            name: 'ACTION',
            choices: ['plan', 'apply'],
            description: 'Select the action to perform'
        )
        choice(
            name: 'ENVIRONMENT',
            choices: ['dev', 'uat', 'prod'],
            description: 'Select the target environment'
        )
        string(
            name: 'BRANCH',
            defaultValue: 'main',
            description: 'Enter the branch name to checkout'
        )
        string(
            name: 'VARIABLE',
            defaultValue: '',
            description: 'Enter the variable value (e.g. key=value)'
        )
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(
                    branches: [[name: "*/${params.BRANCH}"]],
                    extensions: [],
                    userRemoteConfigs: [[url: 'https://github.com/pratikzende882002-hash/Terraform-all-repo.git']]
                )
            }
        }
        stage("terraform init") {
            steps {
                sh("terraform init -reconfigure")
            }
        }
        stage("Action") {
            steps {
                script {
                    def varFlag = params.VARIABLE?.trim() ? "-var '${params.VARIABLE}'" : ""
                    def varFile = "-var-file='envs/${params.ENVIRONMENT}.tfvars'"

                    switch (params.ACTION) {
                        case 'plan':
                            echo "Executing Plan for ${params.ENVIRONMENT}..."
                            sh "terraform plan ${varFile} ${varFlag}"
                            break
                        case 'apply':
                            echo "Executing Apply for ${params.ENVIRONMENT}..."
                            sh "terraform apply --auto-approve ${varFile} ${varFlag}"
                            break
                        default:
                            error 'Unknown action'
                    }
                }
            }
        }
    }
}